name = "OckleberryModsIII"
author = "Ockleberry and Friends"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8e9cc39fda8c71234185c0d7b459774b29ad3e52ac80d22774db28139a639e8"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
